# Generated by Django 3.1.4 on 2021-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(default=None, max_length=200)),
                ('branch', models.CharField(default=None, max_length=200)),
                ('category', models.CharField(default=None, max_length=300)),
                ('File_name', models.CharField(max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(null=True, upload_to='C:\\Users\\Dell\\Desktop\\Team Tachyon\\Hackathon\\Hackathon\\media')),
            ],
        ),
    ]
